apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
  spec:
    containers:
      - name: node-app-argocd
        image: node-app-argocd
        ports:
          - name: node-app-3000
            containerPort: 3000
