apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 532e4adf8ead2a70f741eca8f3dc5924da32c237
- name: node-app
  newName: node-app
  newTag: v1
