apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 884321f0b9644afd25b1792e951760a38c531da3
- name: node-app
  newName: node-app
  newTag: v1
