apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a2ce5b3fe516fbb60b22c63dc0fa5cc9d14ed8f0
- name: node-app
  newName: node-app
  newTag: v1
