apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 43e26346bec793b37d8b23d7ff426c57f5fd93f5
- name: node-app
  newName: node-app
  newTag: v1
