apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0b1bccbeb653f77aba474fdac9d23b154828e39e
- name: node-app
  newName: node-app
  newTag: v1
