apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: b55e10d9e419a13b85ace5f6fa27b0685fa64846
- name: node-app
  newName: node-app
  newTag: v1
