apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1c834649b9e2881baa73e3c52fd3bb315a2491c8
- name: node-app
  newName: node-app
  newTag: v1
