apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a877cc963a3b94ff9b3ebd9e8363eeb86ef04934
- name: node-app
  newName: node-app
  newTag: v1
