apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a4e0291d23a318e9d14ea833ae922310612afa60
- name: node-app
  newName: node-app
  newTag: v1
