apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a2e51c66818c8c744973d3bf9ffa0fc2c46b4bef
- name: node-app
  newName: node-app
  newTag: v1
