apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0793da19a364f433c16dd292a83b6b540cdad47a
- name: node-app
  newName: node-app
  newTag: v1
