apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 28568aeddd646e1598f82ef55735a88916b478c6
- name: node-app
  newName: node-app
  newTag: v1
