apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: b99c52c0970f6b33a31721c0c59ace088abdc6a5
- name: node-app
  newName: node-app
  newTag: v1
