apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: ab74ea93d09bd550ab02cc10a7b29cff0b7150b6
- name: node-app
  newName: node-app
  newTag: v1
