apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0d0305483814e54d08830e6c8d8332426909f89f
- name: node-app
  newName: node-app
  newTag: v1
