apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: be0632ffe698713de1d5da97b9ed80a31ba168cd
- name: node-app
  newName: node-app
  newTag: v1
