apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 812f9f4100d827bcf8362b9f9284770221b0589d
- name: node-app
  newName: node-app
  newTag: v1
