apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: aa185caf4921bd3bd55304be5ee011def3dfe601
- name: node-app
  newName: node-app
  newTag: v1
