apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 73c2328aef57ff1fbef6a932ca2218c150df30e2
- name: node-app
  newName: node-app
  newTag: v1
