apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 03c40117aa97c4577aba38dd5221bd5afabc2c0b
- name: node-app
  newName: node-app
  newTag: v1
