apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 5935db1d640708180dfff4b18dd399190a5f4a3b
- name: node-app
  newName: node-app
  newTag: v1
