apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a550d901774e563c4ca9f239ce90ceda775761b5
- name: node-app
  newName: node-app
  newTag: v1
