apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: ec8bf00581e3866949d3055dd7b6f03a91beb1eb
- name: node-app
  newName: node-app
  newTag: v1
