apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 9b506d5671f266e383f880c1715e4d609a293bb2
- name: node-app
  newName: node-app
  newTag: v1
