apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: bded8199c51a6a7659c2bfd98b0e47fa903d8e64
- name: node-app
  newName: node-app
  newTag: v1
