apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: b6ce84ac048dfb7e4d6078d6687cc4705fd8e926
- name: node-app
  newName: node-app
  newTag: v1
