apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 9fe47a0d47b0361dc635040cab1f7bbdf84d1bd3
- name: 908027386559.dkr.ecr.us-east-1.amazonaws.com/node-app
  newName: 908027386559.dkr.ecr.us-east-1.amazonaws.com/node-app
  newTag: 56bbf64a48bb3c7167f7841ed7a44dbc0341a2c8
