apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 6f6a4a0860cc50075eeb39a44c7c02bf1229afe8
- name: node-app
  newName: node-app
  newTag: v1
