apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 66b4b37826cdc8f99d0c3b229cfcf8d5beb14872
- name: node-app
  newName: node-app
  newTag: v1
