apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 9a03c54c14365488da963266f1900eb4635b2a5b
- name: node-app
  newName: node-app
  newTag: v1
