apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2cc6839a1b81900bebc27a2a6d7f4f51cc5e1829
- name: node-app
  newName: node-app
  newTag: v1
