apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f48b1b2e42cb37013843f82fb6563d260308cddf
- name: node-app
  newName: node-app
  newTag: v1
