apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 3cf0639366569040165e90068a296a0e7c0c9f1e
- name: node-app
  newName: node-app
  newTag: v1
