apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1d31e7d38c819c86f92c369ac27431ef5fbe6d05
- name: node-app
  newName: node-app
  newTag: v1
