apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2c96fe174423441ac6684545dbcb2f57a3bc7ae4
- name: node-app
  newName: node-app
  newTag: v1
