apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 7cbfca1e6a00b87ffe1abf37ddd4cc2755340cc6
- name: node-app
  newName: node-app
  newTag: v1
