apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0440e165f5883e96ed96ce32dcb030e880f6d7e1
- name: node-app
  newName: node-app
  newTag: v1
