apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2e9a53df69994d74b40124569bf849d5459aa522
- name: node-app
  newName: node-app
  newTag: v1
