apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 9ef2474c3ee2a753ffc05a37b1b39745a2ffb823
- name: node-app
  newName: node-app
  newTag: v1
