apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 381f958799c0925be81ccbe2692b94f9b9bb1980
- name: node-app
  newName: node-app
  newTag: v1
