apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 886f3393acb301d92edfa956f67c5450f28df061
- name: node-app
  newName: node-app
  newTag: v1
