apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 478798b413d06147c23e6f28f213e8d59ee98e06
- name: node-app
  newName: node-app
  newTag: v1
