apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 613c0fa8b3037661bbcefbedab14b61ca02de593
- name: node-app
  newName: node-app
  newTag: v1
