apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: e93ecd23b9ab9c30ed51a8c1501bd6ed0042a488
- name: node-app
  newName: node-app
  newTag: v1
