apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 7f19061dfead949d8b4f1734d834a0c956678d8c
- name: node-app
  newName: node-app
  newTag: v1
