apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0bf34f8a97a059dae4f0231b3232c54b43986d8a
- name: node-app
  newName: node-app
  newTag: v1
