apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 90ba57b8f554d73296642aec763e6e00210d46f6
- name: node-app
  newName: node-app
  newTag: v1
