apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 08d9d32f7c846ae4381554325eb3bb72f5901b5a
- name: node-app
  newName: node-app
  newTag: v1
