apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 636c67e0700af540d202fb0294bed13e13cc3f5a
- name: node-app
  newName: node-app
  newTag: v1
