apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 06c03ccd0c7896dc96d50701922d1f1066b11a23
- name: node-app
  newName: node-app
  newTag: v1
