apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2e3d4e2ca141fac6696604c4d7f020fcc4eeac46
- name: node-app
  newName: node-app
  newTag: v1
