apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1bc7e9df529bc3f9054fae959fa41cf0e0497e5a
- name: node-app
  newName: node-app
  newTag: v1
