apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 5766e7c795aba68d1ef6f3b2c984973f65d4d5ff
- name: node-app
  newName: node-app
  newTag: v1
