apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 6d67cd998f03d856a1f722ac2da4b86740f14ac5
- name: node-app
  newName: node-app
  newTag: v1
