apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f08bf3f53a91f582335348cbaee5e41a608c2cf0
- name: node-app
  newName: node-app
  newTag: v1
