apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 3d9bf8d07618895a0efc92493c679bbc94bd7de5
- name: node-app
  newName: node-app
  newTag: v1
