apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 17fa8c18d8216ee903c1949ddd71f5499c9a13bc
- name: node-app
  newName: node-app
  newTag: v1
