apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 65c160b928cbef799f6d63fa135838ded299bbf9
- name: node-app
  newName: node-app
  newTag: v1
