apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: fd6bb080e50c8913a01b360a65f358c1013b3fcc
- name: node-app
  newName: node-app
  newTag: v1
