apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c14cca1651f8005f236459394e8e092071db2694
- name: node-app
  newName: node-app
  newTag: v1
