apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 4dbcb6d6f75b5610187be6fa0154449d21c38978
- name: node-app
  newName: node-app
  newTag: v1
