apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 254ff1b262e572ff3a72d6d2003d5b2855d4e9a5
- name: node-app
  newName: node-app
  newTag: v1
