apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 39eb2f2025e0a15e77793b1947363d41c497cacd
- name: node-app
  newName: node-app
  newTag: v1
