apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 80f5ca97a792eeb0e6d25e3fc7e9f4556e4a9863
- name: node-app
  newName: node-app
  newTag: v1
