apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f34d0b89a43b41fc28999bc38081a5132cc6aa82
- name: node-app
  newName: node-app
  newTag: v1
