apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: cd4ac5433b3767e1f1fc1b1e8d9dd7c712f60ad1
- name: node-app
  newName: node-app
  newTag: v1
