apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: bfb2c647170bf7182e8c80bb0467328bec5531c5
- name: node-app
  newName: node-app
  newTag: v1
