apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: dd02113c8e125cd47a4e50222f927a5012fd372e
- name: node-app
  newName: node-app
  newTag: v1
