apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: aab82a49cf04fceb52608a4799d6e2fbb2b64d0a
- name: node-app
  newName: node-app
  newTag: v1
