apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 8807f1639f4d33f455cf190cfeaec0c826e7c7a6
- name: node-app
  newName: node-app
  newTag: v1
