apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 6a7880ae5dd112176806e0d05b95f5450434fa40
- name: node-app
  newName: node-app
  newTag: v1
