apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 139935f11ef6d4fde8a71ce054f1e68104018e66
- name: node-app
  newName: node-app
  newTag: v1
