apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: fa51ab8e0913cf80086f73ec9cc8c0874c2f0a3d
- name: node-app
  newName: node-app
  newTag: v1
