apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 184f3b40525349eb8cc0454b28db9223f150d633
- name: node-app
  newName: node-app
  newTag: v1
