apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: de42e2341d0a8f3c0d8f8c1cfe1536c705a9b0d5
- name: node-app
  newName: node-app
  newTag: v1
