apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 60366db5e1649ba19b963251a1a2a375d198b750
- name: node-app
  newName: node-app
  newTag: v1
