apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c846b7f0170213169403b76ae3c75368009c9702
- name: node-app
  newName: node-app
  newTag: v1
