apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: aa41d28f71427665b7fff974b875e537bd5cf8c2
- name: node-app
  newName: node-app
  newTag: v1
