apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: d2779ad6d0435366b5e8897b7ab25fe6822791da
- name: node-app
  newName: node-app
  newTag: v1
