apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 4747304fc7f6b84c59dceec1c612958f1b2a57dc
- name: node-app
  newName: node-app
  newTag: v1
