apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 098279b995d565e167b7b175296cf36ff6e6087d
- name: node-app
  newName: node-app
  newTag: v1
