apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c4802bfd54fb78744276d0431371bba07067cc86
- name: node-app
  newName: node-app
  newTag: v1
