apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 01e0589203a183476385d1251278d6bb531504ef
- name: node-app
  newName: node-app
  newTag: v1
