apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: de267e9241d613e96107c0c734323a1546a58558
- name: node-app
  newName: node-app
  newTag: v1
