apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 3c233ab31fc38e131d445eddae573fa181a45969
- name: node-app
  newName: node-app
  newTag: v1
