apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 4830a4a78c3ffdedf4637e78f3a62f6236fafb31
- name: node-app
  newName: node-app
  newTag: v1
