apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c64bd56a9d996b01a6c6a13e371bec666dce4668
- name: node-app
  newName: node-app
  newTag: v1
