apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f11c89f39e849b3bce6dd3bcfaa119ff073e838c
- name: node-app
  newName: node-app
  newTag: v1
