apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: fcbd4b3cb2b85e463c76e0b64963346227f523b0
- name: node-app
  newName: node-app
  newTag: v1
