apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c5bdcd43dd40a99296e11b2061facb4a954d1e26
- name: node-app
  newName: node-app
  newTag: v1
