apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 4f7892c11d2b2d70b6d89fbde42837377f6608d8
- name: node-app
  newName: node-app
  newTag: v1
