apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: dfc8125a398911308da8a3e89b1c26f6255521eb
- name: node-app
  newName: node-app
  newTag: v1
