apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1f8a2f4a91440ace81e2aa8a4ef22e44a458bb5e
- name: node-app
  newName: node-app
  newTag: v1
