apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1a6aab22012a4891811a6be05306370fd6b07e25
- name: node-app
  newName: node-app
  newTag: v1
