apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2aa5f9fe2e6e9311daae2391360bcdf766a20148
- name: node-app
  newName: node-app
  newTag: v1
