apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 61b1458ee1d5b44520eb4dafc9d015b838a641d5
- name: node-app
  newName: node-app
  newTag: v1
