apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 58fa8ba482751cc1df5bace491f506e9dca0c181
- name: node-app
  newName: node-app
  newTag: v1
