apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: d27e39f6bb9fbb86c14cd6fbd2a90b73aeed934b
- name: node-app
  newName: node-app
  newTag: v1
