apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f5dc364a861b1b4faa60ea02cf7ffb80f6ad087b
- name: node-app
  newName: node-app
  newTag: v1
