apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c20bf3a8c25f69f71007c14d88f2c65c0ffaf9cb
- name: node-app
  newName: node-app
  newTag: v1
