apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1be952a65383462290a856fd30e1da6c8ae39e4f
- name: node-app
  newName: node-app
  newTag: v1
