apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 375135590a9a8cd3f223a3c2bcb1f6ef4cae9ce8
- name: node-app
  newName: node-app
  newTag: v1
