apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: b85fb8c612ec19d01c7ee8067dbfd79ba1ebf0ae
- name: node-app
  newName: node-app
  newTag: v1
