apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 8742240fc15f00530d4a14e9c54772021d5bafe1
- name: node-app
  newName: node-app
  newTag: v1
