apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 061e29ee5357fbb0c0a39ea4ab2fd7aa2a595ccf
- name: node-app
  newName: node-app
  newTag: v1
