apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: e13390ae4a024800e9abe55c627f977729bae9c9
- name: node-app
  newName: node-app
  newTag: v1
