apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 26519467706bf27302fb578ac4c3dab84654b2ef
- name: node-app
  newName: node-app
  newTag: v1
