apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2903cd340292039429661328ed88eb29d239b62c
- name: node-app
  newName: node-app
  newTag: v1
