apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f1c34d3c75766b516f445937eed587a28eba775f
- name: node-app
  newName: node-app
  newTag: v1
