apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 9ec4ec7d7fd7de13a91c3ac1fedbd3b45ad895da
- name: node-app
  newName: node-app
  newTag: v1
