apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
namespace: node-app
images:
- name: node-app
  newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app-repo
  newTag: 56bbf64a48bb3c7167f7841ed7a44dbc0341a2c8
