apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 8c5c93eabc6b550e53d73caf05d23f79927b7c73
- name: node-app
  newName: node-app
  newTag: v1
