apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 09aff0ecc54e9e834bd6fedee96ed547cb796b88
- name: node-app
  newName: node-app
  newTag: v1
