apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: eddc9ed597e985d4228a3aca847c92648861a80e
- name: node-app
  newName: node-app
  newTag: v1
