apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0fea43b7113139fa989951d9574bff41a7f2b287
- name: node-app
  newName: node-app
  newTag: v1
