apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a99f914ce43d8204d431188c341afc2f7b37008c
- name: node-app
  newName: node-app
  newTag: v1
