apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 912d83db999c4ba1331d3714d5e0258f4848aa7d
- name: node-app
  newName: node-app
  newTag: v1
