apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 934f7fd0c82eb3e0ffb5f1a84cb09a112762cc63
- name: node-app
  newName: node-app
  newTag: v1
