apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0a8b04c381b61ac68cee3bdb1fe544f74f9a6836
- name: node-app
  newName: node-app
  newTag: v1
