apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 0bac43a92fb3640868fdc2ab47fc010d610d6418
- name: node-app
  newName: node-app
  newTag: v1
