apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: ebdef743559267a25fdf6b5c79872b206547a0a1
- name: node-app
  newName: node-app
  newTag: v1
