apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: d4220626725556a022e8365f14bc80a76ba690c7
- name: node-app
  newName: node-app
  newTag: v1
