apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 837ca128ef91fa8a8d06568e830c50c7cf87f1cf
- name: node-app
  newName: node-app
  newTag: v1
