apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: e210c0143270e9d48c10ca3a8a3f975df2cdd99b
- name: node-app
  newName: node-app
  newTag: v1
