apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 211725097ab3090e9a3b767b2c156f117d593ed0
- name: node-app
  newName: node-app
  newTag: v1
