apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: ba395369314f75a088f6e9542682dde61634edf8
- name: node-app
  newName: node-app
  newTag: v1
