apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 5762fed308afd8bdef76ae58ff8723b18324d7d9
- name: node-app
  newName: node-app
  newTag: v1
