apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 6b3d2f3ae5947708c3a6cb2067a1e752eb40d4a7
- name: node-app
  newName: node-app
  newTag: v1
