apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: d611616b3e747d8f20fcef1960fda4acaeaed845
- name: node-app
  newName: node-app
  newTag: v1
