apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 11fb3a216be27220ca375f75ce82011109135bc8
- name: node-app
  newName: node-app
  newTag: v1
