apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 6fdd4cc9e972618d043d1a440a0d524a80329393
- name: node-app
  newName: node-app
  newTag: v1
