apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 8671ef69f3d7db8cf599045aa2942cc2f81b4aa1
- name: node-app
  newName: node-app
  newTag: v1
