apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: f36389f108b2e0e50a80b7c62c272d15d87c1e89
- name: node-app
  newName: node-app
  newTag: v1
