apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 19d8f8702459e0702b3f4da5aa00f9ec7f21506d
- name: node-app
  newName: node-app
  newTag: v1
