apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 860d65086db8c6badc1507145dc43b841b8e8498
- name: node-app
  newName: node-app
  newTag: v1
