apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 46b98c093996908044ef016fed848af99337df3f
- name: node-app
  newName: node-app
  newTag: v1
