apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: d70fe638b0455a8b0f8f43ce5955cca4705b4c4f
- name: node-app
  newName: node-app
  newTag: v1
