apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 480c21b541f2610ea4d09795d083dab424a5bd67
- name: node-app
  newName: node-app
  newTag: v1
