apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a0766d1f9179e255cf3048e535013b50931000c0
- name: node-app
  newName: node-app
  newTag: v1
