apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 72e9e5209fdcd33f26df946784bf515ebcb06ed1
- name: node-app
  newName: node-app
  newTag: v1
