apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 5eb6ed90986e94e3b150967afc91488aac2ecbd8
- name: node-app
  newName: node-app
  newTag: v1
