apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c97a3bacd86a483ab9c42f951efc5501e03d2995
- name: node-app
  newName: node-app
  newTag: v1
