apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 28bc29f0374cbecb5575d4ff70ce77dc53049d3d
- name: node-app
  newName: node-app
  newTag: v1
