apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 2eef23d8cb854def3ba5f152c6bf376a9a1048f8
- name: node-app
  newName: node-app
  newTag: v1
