apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 48d805863c184678543f4b1d855ea9a3044573d5
- name: node-app
  newName: node-app
  newTag: v1
