apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 59d8ac42fc608cbf8f52fc46d05dee3b2af71969
- name: node-app
  newName: node-app
  newTag: v1
