apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 4f1e8c8429517fe075a94698c7b41cc35a4512f6
- name: node-app
  newName: node-app
  newTag: v1
