apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 9550c83ab8d88db900e193b4ed1e35eecd59c1cd
- name: node-app
  newName: node-app
  newTag: v1
