apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: ec290db398b3b108fa8dfc87df902d643dd55451
- name: node-app
  newName: node-app
  newTag: v1
