apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 709ecc53ea466088f14449b9d307fef6c04f7328
- name: node-app
  newName: node-app
  newTag: v1
