apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: a86c2a196d75e86d815e47da6ecf6ed15b3e3702
- name: node-app
  newName: node-app
  newTag: v1
