apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 58921051d2bec84317e41fe193c8fce2a4975f03
- name: node-app
  newName: node-app
  newTag: v1
