apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 4064a745b1538c922ad45f4a1d242931e4f72567
- name: node-app
  newName: node-app
  newTag: v1
