apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 6504c93ad0510ca857eaa5c4165771739409a006
- name: node-app
  newName: node-app
  newTag: v1
