apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: df90a38873cab36e0982ed7f0ef561d26d2003d5
- name: node-app
  newName: node-app
  newTag: v1
