apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1c391b76d980262317373e80c73c84b545fb028f
- name: node-app
  newName: node-app
  newTag: v1
