apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 85dddc0f4eefc937ef755552b9657e37acffa7ee
- name: node-app
  newName: node-app
  newTag: v1
