apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 3e2f99f501e9d060072d342d2944d2cbe91e241b
- name: node-app
  newName: node-app
  newTag: v1
