apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 7a1b824c0c4d5d2b624ad22b413723ae92930626
- name: node-app
  newName: node-app
  newTag: v1
