apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: c3b73126e754e498990d13351187440cc83ee96d
- name: node-app
  newName: node-app
  newTag: v1
