apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 60fd421dcfa4c2ae881135b5c85766074618f4b2
- name: node-app
  newName: node-app
  newTag: v1
