apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 1f4e2d4146f7fe22bc4441fc6d30947bbf2b6ad6
- name: node-app
  newName: node-app
  newTag: v1
