apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: dce7c2c75a6247077e3d2a3810570591f7462711
- name: node-app
  newName: node-app
  newTag: v1
