apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: b965fd1c0351bc1b67d88734d38b185838d23683
- name: node-app
  newName: node-app
  newTag: v1
