apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: fe59a55a7049fcf371e341347d2a62f13f464ef8
- name: node-app
  newName: node-app
  newTag: v1
