apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: b6f3556774650cfdd4b61cfa9f754c85e1f309dd
- name: node-app
  newName: node-app
  newTag: v1
