apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 5065e9b4c4d9e8ef90d6571aebbb7f9db5ce1d9c
- name: node-app
  newName: node-app
  newTag: v1
