apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 8293824830415f01802c79d56c9b8c07890fdfc7
- name: node-app
  newName: node-app
  newTag: v1
