apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
namespace: node-app
images:
- newName: /
  newTag: 06d7ecb3960b077c2e6aa1fec9a9049523a35ab6
- name: node-app
  newName: node-app
  newTag: v1
